import type { NtmArticle } from '@/types/database'

// 실제 최신 연구/뉴스 기반 샘플 데이터
export const sampleArticles: NtmArticle[] = [
  {
    id: 'article-1',
    source: 'PubMed',
    title_original: 'Omadacycline-Based Regimen for Treatment of M. abscessus Pulmonary Disease',
    title_ko: '오마다사이클린 기반 M. abscessus 폐질환 치료 요법',
    summary_ko: '새로운 경구 항생제 오마다사이클린이 M. abscessus 폐감염 환자에서 유망한 결과를 보였습니다. 기존 주사 치료를 경구약으로 대체할 수 있는 가능성이 열리고 있습니다. 12명의 환자 중 8명(67%)에서 객담 배양 전환이 확인되었습니다.',
    hope_score: 85,
    relevance_score: 95,
    category: 'new_drug',
    published_at: '2026-02-15',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
  {
    id: 'article-2',
    source: 'ClinicalTrials.gov',
    title_original: 'Phase 2 Trial of Phage Therapy for M. abscessus Lung Infection',
    title_ko: 'M. abscessus 폐감염 대상 파지 치료 2상 임상시험 시작',
    summary_ko: '피츠버그 대학 연구팀이 M. abscessus에 대한 파지(바이러스) 치료의 공식 임상시험을 시작했습니다. 항생제가 듣지 않는 환자에게 맞춤형 파지를 사용하여 균을 공격하는 혁신적인 접근법입니다. 전 세계에서 기존 치료에 실패한 환자들이 참여하고 있습니다.',
    hope_score: 90,
    relevance_score: 90,
    category: 'phage',
    published_at: '2026-01-20',
    url: 'https://clinicaltrials.gov/',
  },
  {
    id: 'article-3',
    source: 'PubMed',
    title_original: 'Tedizolid Shows Superior Safety Profile in Long-term NTM Treatment',
    title_ko: '테디졸리드, 장기 NTM 치료에서 우수한 안전성 확인',
    summary_ko: '차세대 항생제 테디졸리드가 기존 리네졸리드보다 부작용이 현저히 적으면서도 M. abscessus에 대한 효과는 유지하는 것으로 확인되었습니다. 특히 12개월 이상 장기 복용 시 신경독성과 혈액 부작용이 크게 줄었습니다.',
    hope_score: 80,
    relevance_score: 85,
    category: 'new_drug',
    published_at: '2026-01-10',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
  {
    id: 'article-4',
    source: 'Research',
    title_original: 'Korean NTM Registry: 5-Year Outcomes in M. abscessus Patients',
    title_ko: '한국 NTM 등록부: M. abscessus 환자 5년 치료 성과 발표',
    summary_ko: '한국 NTM 등록부의 5년간 데이터 분석 결과, M. abscessus 환자의 치료 성공률이 꾸준히 향상되고 있습니다. 특히 새로운 약제 조합을 사용한 그룹에서 멸균 성공률이 45%에서 62%로 상승했습니다. 서울아산병원을 포함한 전국 12개 병원의 데이터입니다.',
    hope_score: 88,
    relevance_score: 98,
    category: 'research',
    published_at: '2025-12-05',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
  {
    id: 'article-5',
    source: 'News',
    title_original: 'Insmed Announces Positive Results for ARIKAYCE in M. abscessus',
    title_ko: 'ARIKAYCE(아미카신 리포좀 흡입), M. abscessus 적응증 확대 임상 긍정 결과',
    summary_ko: '인스메드사가 아미카신 리포좀 흡입제(ARIKAYCE)의 M. abscessus 폐질환 대상 임상시험에서 긍정적 결과를 발표했습니다. 기존 정맥주사 아미카신의 부작용을 줄이면서 폐에 직접 약물을 전달하는 방식입니다. FDA 승인 신청을 준비 중입니다.',
    hope_score: 92,
    relevance_score: 93,
    category: 'new_drug',
    published_at: '2025-11-18',
    url: 'https://insmed.com/',
  },
  {
    id: 'article-6',
    source: 'PubMed',
    title_original: 'Immune-Boosting Strategies for NTM Patients: Exercise and Nutrition Review',
    title_ko: 'NTM 환자의 면역력 강화: 운동과 영양 종합 리뷰',
    summary_ko: '규칙적인 중등도 운동(하루 30분 걷기)과 비타민D, 아연 보충이 NTM 환자의 면역 기능을 의미있게 개선하는 것으로 나타났습니다. 특히 위절제술 후 영양흡수가 저하된 환자에서 비타민D 보충이 중요합니다.',
    hope_score: 75,
    relevance_score: 90,
    category: 'immunity',
    published_at: '2025-10-22',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
]
